### ISSUE TITLE
Testing author activation

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat-Frontend-Tests#7]
* login in librecat as test user
* add a new book publication
* fill out the lastname 'monroe'
* click on 'activate author'

The author field should be automatically completed to 'Marilyn Monroe'.

alternative test using the previous name of Marylin: Norma Jeane Mortenson

* login in librecat as test user
* add a new book publication
* fill out the lastname 'Mortenson'
* click on 'activate author'

The author field should be automatically completed to 'Marilyn Monroe'.

**Comment by petrakohorst** [comment]
Is this test already for the new "multiple old names"? If so then the test needs to be changed a little. The mechanism works like this:

If a person has no old_names, only a current name:
- login in librecat as test user
- add a new book publication
- fill out the lastname "einstein"
- click on 'activate author'

The author field should be automatically completed to 'Albert Einstein'

---

For any person with an old_name:
- login in librecat as test user
- add a new book publication
- fill out the last name 'monroe'
- click on 'activate author'

A modal should appear, suggesting both the current and the old name to choose from.
- click on the name "Marilyn Monroe"

The author field should be completed to 'Marilyn Monroe'

---

Alternative test using old name:
- login in librecat as test user
- add a new book publication
- fill out the last name "Mortenson"
- click 'activate author'

A modal should appear, suggesting both the current name "Marilyn Monroe" and the old name "Norma Jeane Mortenson" to choose from.
- click on the name "Norma Jeane Mortenson"

The author field should be completed to 'Norma Jeane Mortenson'

---

In all cases the chosen name (NOT the current name by default) should appear in the database/index. There is no longer a lookup of author names during indexing because authors should be able to add their old names to a publication.

---

And this test presupposes that
- Albert Einstein has no old name set,
- Marilyn Monroe has the old name "Norma Jeane Mortenson" set

**Comment by verheyenkoen** [comment]
Tests added:

    $(npm bin)/cypress run --spec cypress/integration/librecat/record/fields/author.spec.js


```
  The author field
    For unknown authors
      ✓ should not be possible to activate the author (1420ms)
    For authors without an old name
      ✓ should be possible to activate the author (1050ms)
    For authors with an old name
      ✓ should be possible to activate the author by current name (1420ms)
      ✓ should be possible to activate the author by old name (2066ms)
```
